create table "public"."course_outlines" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    "username" character varying not null,
    "subject" text not null,
    "content" text not null,
    "user_id" uuid not null
);


alter table "public"."course_outlines" enable row level security;

CREATE UNIQUE INDEX course_outlines_pkey ON public.course_outlines USING btree (id);

alter table "public"."course_outlines" add constraint "course_outlines_pkey" PRIMARY KEY using index "course_outlines_pkey";

alter table "public"."course_outlines" add constraint "public_course_outlines_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."course_outlines" validate constraint "public_course_outlines_user_id_fkey";

grant delete on table "public"."course_outlines" to "anon";

grant insert on table "public"."course_outlines" to "anon";

grant references on table "public"."course_outlines" to "anon";

grant select on table "public"."course_outlines" to "anon";

grant trigger on table "public"."course_outlines" to "anon";

grant truncate on table "public"."course_outlines" to "anon";

grant update on table "public"."course_outlines" to "anon";

grant delete on table "public"."course_outlines" to "authenticated";

grant insert on table "public"."course_outlines" to "authenticated";

grant references on table "public"."course_outlines" to "authenticated";

grant select on table "public"."course_outlines" to "authenticated";

grant trigger on table "public"."course_outlines" to "authenticated";

grant truncate on table "public"."course_outlines" to "authenticated";

grant update on table "public"."course_outlines" to "authenticated";

grant delete on table "public"."course_outlines" to "service_role";

grant insert on table "public"."course_outlines" to "service_role";

grant references on table "public"."course_outlines" to "service_role";

grant select on table "public"."course_outlines" to "service_role";

grant trigger on table "public"."course_outlines" to "service_role";

grant truncate on table "public"."course_outlines" to "service_role";

grant update on table "public"."course_outlines" to "service_role";


